### ISSUE TITLE
Send with .iq file

### ISSUE THREAD

**Issue by Lucstay11** [rgerganov/tesla-opener#1]
Hi i am using **RPtix** on Raspberry to send signals. Could you generate me a file that does the same thing on the tesla but with an .iq file? Or if you feel able to explain it to me so that I can create it myself. thank you

**Comment by rgerganov** [comment]
I have added a simple program which generates IQ files using 2M sample rate. You can find the output in the `iq` dir. It produces both signed and unsigned `u8` IQ files.
